
spring:
  datasource:
    url: jdbc:h2:mem:person;MODE=postgresql;INIT=CREATE SCHEMA IF NOT EXISTS person
    username: sa
    password: 
    initialization-mode : always
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
     ddl-auto: create
    properties:
     hibernate:
      default_schema : person
# logging:
#   level:
#     org.springframework.data : DEBUG